services:
  mysql:
    image: mysql:8.0
    container_name: gripinvest_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: investment_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  backend:
    build: ./backend
    container_name: gripinvest_backend
    env_file:
      - ./backend/.env.docker
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 10s
      retries: 30
      timeout: 10s

  frontend:
    build: ./frontend
    
    container_name: gripinvest_frontend
    ports:
      - "5173:5173"
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./frontend:/usr/src/app
    command: npm run dev -- --host 0.0.0.0
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:5173 || exit 1"]
      interval: 10s
      retries: 10
      timeout: 10s

volumes:
  mysql_data:
